# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 3.6
python: 3.6

# Install the codecov pip dependency
install:
  - pip install -r requirements.txt
  - pip install codecov

# Run the unit test
script:
  - cd src
  - cp appstore/settings/local.sample.env appstore/settings/local.env
  - coverage run manage.py test
  - cd ..

# Push the results back to codecov
after_success:
  - codecov